In [1]:
import numpy as np

#creating array of 10 zeros
arr = np.zeros(10)
print(arr)

#create array of 10 ones
arr = np.ones(10)
print(arr)

#create array of 10 fives
arr = np.ones(10) * 5
print(arr)

#create array of numbers from 10 to 50 (including)
arr = np.arange(10, 51)
print(arr)

#create array 3x3 with numbers 0 to 8
arr = np.arange(9).reshape(3, 3)
print(arr)

#create 3x3 identity matrix
arr = np.eye(3)
print(arr)

#random number 0 -1
num = np.random.rand(1)
print (num)

#25 random numbers
arr = np.random.random((5,5)) + 1
print(arr)

#matrxi below
arr = np.linspace(0.01, 1, 100).reshape(10, 10)
print(arr)

#20 uniformly inreasing numbers from 0 to 1
arr = np.linspace(0, 1, 20)
print(arr)

#task given
mat = np.arange(1, 26).reshape(5,5)
print(mat[2:, 1:])

print(mat[3, 4])

#print(mat[0:3, 1])
print(np.hsplit(mat[0:3, :], 5)[1])
print(mat[:, 3:4])

print(mat[4, :])

print(mat[3:5, :])

print(np.sum(mat))
print(np.std(mat))
print(np.sum(mat, axis = 0))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.62117923]
[[1.08919931 1.5115205  1.91056171 1.80950515 1.90807302]
 [1.50333615 1.01283643 1.35319169 1.84945539 1.16592541]
 [1.48233379 1.84784115 1.2203611  1.79511971 1.73936244]
 [1.50720097 1.2926778  1.2349105  1.18090651 1.9530206 ]
 [1.55782587 1.75624853 1.16693738 1.91339529 1.44482384]]
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0