In [1]:
import numpy as np
a = [1, 2, 3, 5]

In [2]:
a


[1, 2, 3, 5]

In [3]:
b = a[:]

In [4]:
b


[1, 2, 3, 5]

In [5]:
b[2] = 10

In [6]:
a


[1, 2, 3, 5]

In [7]:
c = a


In [8]:
c[2] = 10

In [9]:
a

[1, 2, 10, 5]

In [10]:
a = np.random.rand(3, 4)

In [11]:
a


array([[0.03466075, 0.44479014, 0.73230541, 0.99535564],
       [0.12776745, 0.58980771, 0.31945286, 0.13102817],
       [0.41200434, 0.60461108, 0.64042902, 0.29904836]])

In [12]:
b = a.reshape(2, 6)

In [13]:
b


array([[0.03466075, 0.44479014, 0.73230541, 0.99535564, 0.12776745,
        0.58980771],
       [0.31945286, 0.13102817, 0.41200434, 0.60461108, 0.64042902,
        0.29904836]])

In [14]:
b[0, 0] = 100

In [15]:
a

array([[100.        ,   0.44479014,   0.73230541,   0.99535564],
       [  0.12776745,   0.58980771,   0.31945286,   0.13102817],
       [  0.41200434,   0.60461108,   0.64042902,   0.29904836]])

In [17]:
a.reshape(1, 12)

array([[100.        ,   0.44479014,   0.73230541,   0.99535564,
          0.12776745,   0.58980771,   0.31945286,   0.13102817,
          0.41200434,   0.60461108,   0.64042902,   0.29904836]])

In [29]:
a = np.arange(25).reshape(5, 5 )

In [31]:
a[::-1]


array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])